# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

netLagCppLoop <- function(mat, pdistmat, pathdist, decay, y, normalization, reciprocal) {
    .Call('xergm_netLagCppLoop', PACKAGE = 'xergm', mat, pdistmat, pathdist, decay, y, normalization, reciprocal)
}

